### ISSUE TITLE
Guide keybinds not updating

### ISSUE THREAD

**Issue by PeteWay** [oitsjustjose/Twotris#13]
When keybinds are changed after opening the game, the guide references on page 5 do not update. (Tested twice, to be sure that was the issue)

**Comment by PeteWay** [comment]
Maybe having an update method like we do with the fonts might work? I'm not sure, but I'll be thinking it over tonight at work.

**Comment by oitsjustjose** [comment]
They *should* update on restart. You see, the guide is set up kind of like the Algorithms Analysis Linked List: they don't have knowledge of their position, just which "node" (i.e.: page) is *next*. So, in order to update the ***one*** page which refers to keybinds, we'd have to re-instantiate every single page along the way.


Instantiating the tutorial pages actually takes a pretty long time: f you think about it, it's creating Page 1, which creates Page 2, which creates ... you get the point. 

Each page requires generating a set of Fake Tetrominos to sit in the corner. In addition, each page requires loading up the font and a few other things.

I'm not saying this can't be solved, but what I am saying is that: In general, the use-case of the tutorial will be: 

- On first launch (in which they haven't had a chance to change the keybinds anyway, if I do the "Auto-tutorial" thing the way I plan)
- To teach a friend (at which point they've probably played it a while, and restarted the game at least once).

I don't think fixing this is hugely necessary if you analyze [performance] cost vs benefit
